### ISSUE TITLE
redirect to dashboard no working

### ISSUE THREAD

**Issue by Mahmoudz** [Porto-SAP/Hello-API#109]
@llstarscreamll the `return redirect('dashboard');` in the `loginAdmin` of `app/Containers/Authentication/UI/WEB/Controllers/Controller.php` controller doesn't work. And keeps showing credentials incorrect, after updating the URL. Changing that to `return view('authentication::dashboard');` will make it work, but that's not the right way to do it. The URL must be updated.

**Comment by llstarscreamll** [comment]
Hi @Mahmoudz , yes, it's related to the Authentication middleware and the overrides from the Kernel web middlewares when loading middlewares from containers!! OMG!! middleware everywhere!! The session never starts and when the redirection from login take effect the Authentication never takes the user as authenticated because the session data was never persisted... And other many errors consequent since the kernel web middlewares never init!! I just woke up, in a moment I will take your observations on the PR's...

**Comment by llstarscreamll** [comment]
@Mahmoudz , I have send the PR's tell me if I can help with anything...
