### ISSUE TITLE
How to make containers compatible with "standard" Laravel App?

### ISSUE THREAD

**Issue by llstarscreamll** [Porto-SAP/Hello-API#85]
Hi, as the title says, would be great that containers could be compatible with "standard" Laravel apps, any ideas on how to achieve this?

- Maybe make the PORTO layer like a Laravel vendor package? The PORTO package would be a containers dependency (obviously)...
- But what about the "bootstrap/app.php" file?
- What about the Hello-API default containers?

Would be awesome make use of containers everywhere on Laravel, the authentication and user scaffolding are better than the default Laravel offers... or maybe is this a bad idea?

Thanks!!!

**Comment by Mahmoudz** [comment]
Well everything is possible and we can always find solutions to do whatever we need (it's not so easy but not impossible). 

But anyway I don't see any use case for that! (could you please share your use case). Because one of the concepts of Hello API is to get rid of the `ugly`! folder structure of Laravel in the `app`, where every user place his classes anywhere he likes and it's hard to read people's code because of that..

And putting the Porto layer in the vendor, is gonna lead to slower development.. but that's not the only reason, that layer is meant to be used as place to hold shared code between your containers so it must be tied to your project code very well. (Example, if you wanna apply some sort of code on every controller you simply put that code in the container abstract folder in the port layer..). 

Hope my answer helps. And again I'm always open to any kind of suggestions like this. Thanks.

**Comment by llstarscreamll** [comment]
You are right, and I understand all the advantages from Porto architecture. But how we can put together  an Laravel standard app or package and the Hello-API container? maybe include de Laravel package on Hello-API app? Say something like Customers (Laravel app or package) and Employees (Hello-API container), the purpose is reuse, avoid to write the app again (customers or employees) only for use in one side or other...

Thanks in advance!!

**Comment by Mahmoudz** [comment]
@llstarscreamll I'm sorry I didn't understand what you mean!! Can you give more examples?

**Comment by llstarscreamll** [comment]
I think that I will go with the Porto philosophy from now, @Mahmoudz thank you very much for this amazing project!! :smile:

**Comment by Mahmoudz** [comment]
@llstarscreamll cool :D you're more than welcome
